[build]
builder = "NIXPACKS"
buildCommand = "./railway_setup.sh"

[deploy]
startCommand = "gunicorn 'app:create_app()' --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments]
  [environments.production]
  enableConsoleCommands = false
  showHealthStatus = true
