[build]
builder = "nixpacks"
buildCommand = "chmod +x railway_setup.sh && ./railway_setup.sh"

[deploy]
startCommand = "gunicorn 'app:create_app()' --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Explicitly set Python
[nixpacks]
python_version = "3.9"
